[build]
rustc-wrapper = "sccache"

[target.x86_64-apple-darwin]
rustflags = [
    "-Ctarget-cpu=native",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-Ctarget-cpu=native",
]

[net]
git-fetch-with-cli = true

[registries.crates-io]
protocol = "sparse"
