#!/usr/bin/env bash

cd "$(dirname "$0")"
DOTFILES=$(pwd -P)

set -e

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

if [[ $OSTYPE == "darwin"* ]]; then
	if [ ! $(which brew) ]; then
		info "installing homebrew"
		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
		success
	else
		info "Homebrew already installed"
	fi

	info "installing dependencies from Brewfile"
	brew bundle --file $DOTFILES/brew/Brewfile --no-lock
fi

# on macos asdf is installed using homebrwe.
if [[ $OSTYPE != "darwin"* ]]; then
	info "installing asdf using git"
	git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.0
fi

info "installing rustc"
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -- -y --no-modify-path

info "installing ghcup"
BOOTSTRAP_HASKELL_NONINTERACTIVE=1 \
BOOTSTRAP_HASKELL_INSTALL_STACK=false \
BOOTSTRAP_HASKELL_INSTALL_HLS=true \
BOOTSTRAP_HASKELL_ADJUST_BASHRC=false \
curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh

info "installing oh-my-zsh"
curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh -c -- --keep-zshrc --unattended

