#!/usr/bin/env sh
#
# Run all dotfiles installers.
# https://github.com/holman/dotfiles/blob/master/script/install

set -e

cd "$(dirname $0)"/..

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
