import = ["/Users/bokleynen/.config/alacritty/base16_default_dark.toml"]
live_config_reload = true
working_directory = "None"

[font]
# blinking = "On"
size = 12.0
# style = "Block"

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "MonoLisa Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bq"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bx"
key = "X"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bz"
key = "Z"
mods = "Command"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000

[shell]
args = ["-l"]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_title = true
# gtk_theme_variant = "None"
opacity = 1.0
startup_mode = "Windowed"
title = "Alacritty"
